# application.properties or application.yml contains global application properties,
# and sent to any and all configuration clients.

protected-areas:
  - 
    name: Site 1
    type: POLYGON
    warn-time: 90
    display-warning-area: false
    coordinates:
      - 
        latitude: 34.6749300051062
        longitude: -86.6914982250725
      - 
        latitude: 34.6749300051062
        longitude: -86.6814982250725     
      - 
        latitude: 34.6849300051062
        longitude: -86.6814982250725           
      - 
        latitude: 34.6849300051062
        longitude: -86.6914982250725 

