don-configuration:
    devices:
	    DukeV51:
		    type: DukeV5
			symbol-code: SFGPUUMSEJ*****
			latitude: 34.641
			longitude: -86.695
			altitude: 20.0			
			range: 10000
            command-uri: udp://127.0.0.1:30051
            data-uri: udp://127.0.0.1:30052
	    DukeV52:
		    type: DukeV5
			symbol-code: SFGPUUMSEJ*****
			latitude: 34.65
			longitude: -86.698
			altitude: 20.0			
			range: 10000
            command-uri: udp://127.0.0.1:30055
            data-uri: udp://127.0.0.1:30056
	    Nighthawk-1:
		    type: Nighthawk
			symbol-code: SFGPUCFTF-*****
			latitude: 34.64
			longitude: -86.69
			altitude: 22.0		
			home-latitude: 34.6
			home-longitude: -86.6
			home-altitude: 22.0			
			azimuth-multiplier: 25
			elevation-multiplier: 15
            command-uri: udp://127.0.0.1:14305
            data-uri: udp://127.0.0.1:14306
			eo-stream-uri: rtsp://127.0.0.1:4445
			ir-stream-uri: rtsp://127.0.0.1:4444
	    Crows-1:
		    type: Crows
			symbol-code: SFGPEWR---*****
			latitude: 34.643
			longitude: -86.694
			altitude: 22.0	
            ptu-designation: 12345			
            command-uri: udp://127.0.0.1:14800
            priority-track-uri: udp://127.0.0.1:14801		
			eo-stream-uri: rtsp://127.0.0.1:4445/stream			
