## this is the specific properties for the don.service.device-mgr application
## it will be fed to that via the configuration server

exchanges:
  commands       : device.commands
  tracks         : device.detections
  device-status  : device.status  
  service-status : service.status
  

mas-in-uri: 127.0.0.1:30053
mas-out-uri-threats: 127.0.0.1:14508
mas-out-uri-tracks: 127.0.0.1:14506
mas-publish-rate: 2000