## this is the specific properties for the don.service.device-mgr application
## it will be fed to that via the configuration server

exchanges:
  commands       : device.commands
  tracks         : device.detections
  device-status  : device.status  
  service-status : service.status
  
mas-config:
  mas-in-uri: 127.0.0.1:30053
  mas-out-uri-threats: 127.0.0.1:14508
  mas-out-uri-tracks: 127.0.0.1:14506

devices:
  -
    name: DukeV51
    type: DukeV5
    symbol-code: SFGPUUMSEJ*****
    range: 10000
    debug-level: DEBUG
    position: 
        lla: { latitude: 34.65, longitude: -86.698, altitude: 20 }
        ecef: { x: 302543.4355281, y: -5243872.413, z: 3605987.6639 }
    comms:
        command-uri: udp://127.0.0.1:30055
        data-uri: udp://127.0.0.1:30056
