## this is the specific properties for the don.service.device-mgr application
## it will be fed to that via the configuration server

exchanges:
  commands       : device.commands
  tracks         : device.detections
  device-status  : device.status  
  service-status : service.status

devices:
  -
    name: DukeV51
    type: DukeV5
    symbol-code: SFGPUUMSEJ*****
    range: 10000
    position: 
        lla: { latitude: 34.65, longitude: -86.698, altitude: 20 }
        ecef: { x: 302543.4355281, y: -5243872.413, z: 3605987.6639 }
    comms:
        command-uri: udp://127.0.0.1:30055
        data-uri: udp://127.0.0.1:30056

  -
    name: Nighthawk1
    type: Nighthawk
    symbol-code: SFGPUCFTF-*****
    position: 
        lla: { latitude: 34.64, longitude: -86.69, altitude: 8.0 }
        ecef: { x: 303311.45, y: -5244449.859, z: 3605068.201 }
    comms:
        command-uri: udp://127.0.0.1:14305
        data-uri: udp://127.0.0.1:14306
        eo-stream-uri: udp://127.0.0.1:4445
        ir-stream-uri: udp://127.0.0.1:4444
    options:
        azimuth-multiplier: 25
        azimuth-rate-multiplier: 5
        elevation-multiplier: 15
        elevation-rate-multiplier: 5
